### ISSUE TITLE
MINOR: Extra Suggested Module in composer.json

### ISSUE THREAD

**Issue by gordonbanderson** [heyday/silverstripe-cacheinclude#12]
hi @heyday

Firstly I wish to say that I like your approach to this problem, indeed getting it down to zero queries would be ideal.  When I first looked at this same problem from another angle what I saw was a separate database query made for each section of the page that had a partial fragment, and sometimes these were the same query (but for a different rendering).  I eventually opted for an approach where *all* of the queries required to create partial fragment cache keys were executed in a singular SQL statement.  The resultant code is available at https://github.com/gordonbanderson/weboftalent-cachekey-helper and is working well for me.  However it not perfect, in that for example there is no way to cache by GalleryPic belonging to a particular Gallery, if a GalleryPic in another Gallery was edited all Gallery caches would be busted.

When I wrote the above I noticed that LastEdited was not indexed, which means that an entire table has to be checked when checking for Max('LastEdited'), I wrote a simple module to deal with this, https://github.com/gordonbanderson/weboftalent-index-lastedited - it was this module I am suggesting could be added to the 'suggested modules' section of composer.json

As I type though, I note your invalidation example uses the Created field which the above module does not cover.  I see 3 approaches to fixing this issue:
* Raise a pull request to fix it in core to add indexes for Created and LastEdited for all DataObjects
* Have a module such as mine above that covers both LastEdited and Created and either require said module or add it as a suggested install in composer.json
* Change the documentation to suggest adding indexes where appropriate.

Whilst I have not double checked (it is beer o'clock on Friday in Thailand!), are each of the invalidation queries executed separately?  If so then perhaps taking the approach I did in weboftalent-cachekey-helper, namely getting all of the keys in one SQL statement, so that at most only that one statement is required.

Regards

Gordon

**Comment by camspiers** [comment]
Hey @gordonbanderson,

I'd like to better understand what you are trying to achieve as I don't quite understand it, nor do I understand what you are proposing here.

CacheInclude doesn't use any database queries for its cache invalidation. You are expected to do the cache invalidation yourself or use one of the in-built mechanisms provided by the `InvalidationExtension`. Here is a description of how the inbuilt mechanisms work:

All invalidation works by determining what needs to be invalidated at the time that a DataObject write occurs. There is no checking of cache validity at the time you try to fetch the cached version. The cached version of the content is simply there or it is not (keys are generated by the key generator). There is one exception to this, and this is when caching by time period (e.g. for 5 mins). In this case it is handled by the doctrine cache.

- Invalidation by DataObject class name at time of write
- Invalidation by invalidation rules that run at the time of write

With CacheInclude it is possible, and indeed the entire purpose to not do DB queries at the time of cache getting, because you want to avoid talking to the database when you are in the request cycle. Instead we do invalidation are write time, because write happen less often.

**Comment by camspiers** [comment]
This module was originally created prior to SilverStripe's partial caching, and as I saw the approach of avoiding DB queries during cache getting to be a desirable property, this module exists as an alternative to SilverStripe's inbuilt partial caching solution.

**Comment by camspiers** [comment]
So to be clear, the example that uses the invalidation rules, that rule doesn't run unless you write/save an instanceof CreativeProfile.

This particular example has no context, but to give you an idea, what it does is it invalidate the cache if the item you are saving is one of the 4 most recently created profile.

```
 invalidation_rules:
    - "instanceof(item, 'CreativeProfile') and item.ID in list('CreativeProfile').sort('Created DESC').limit(4).getIDList()"
```

**Comment by gordonbanderson** [comment]
hi @camspiers 

Thanks for the background, I didn't realise it was an alternative to partial caching and indeed pre-dated it.   My goal, like yours, was to reduce the number of database queries but I am checking at rendering time, not write time.  I have simply collated all of the queries made for partial caching into one SQL statement to reduce the number of database calls.  My initial motivation for writing the module was that I had one client project I was given to fix performance on a site, and likes of 30,000 SQL queries (I am not joking) were executed just to render the number of message notifications a la Facebook.

I wish I'd known about this module sooner.  Thanks for the brief description of how it works, I will certainly have a play with it

Cheers

Gordon

**Comment by camspiers** [comment]
You're welcome @gordonbanderson. Definitely have a play, the API is very similar to SilverStripe's partial caching, so it shouldn't be too difficult to migrate.
